// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Ols87

//@version=5
strategy("BTC - 1W", overlay = true, initial_capital = 1000, currency = 'USD', default_qty_type = strategy.percent_of_equity, default_qty_value = 100)
// FIB
dist = ta.highest(high, 15) -  ta.lowest(low,  15)
mid = ta.highest(high, 15) - (dist / 2)
color = color.new(color.white, 0)
mid_ma = ta.wma(mid, 15)
bull_trend = close > mid_ma 
bear_trend = close < mid_ma

if bull_trend
    color:= color.new(color.green, 0)
if bear_trend
    color:= color.new(color.red, 0)
plot(mid_ma, color=color)

start_date = timestamp("2018-06-06T00:00:00")

if(time > start_date)
    if bull_trend
        strategy.entry("LONG", strategy.long)
    if bear_trend
        strategy.close("LONG")
